# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
