# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170809_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='taken_date',
            new_name='date_taken',
        ),
    ]
