# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_result_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
