# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20170809_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
