# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_section_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='manual',
        ),
        migrations.AddField(
            model_name='result',
            name='final_score',
            field=models.BooleanField(default=True),
        ),
    ]
