# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 05:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0010_auto_20170810_0912'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('section', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('participant', 'section')]),
        ),
    ]
