# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20170810_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
