# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20170811_1529'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('quiz', 'number')]),
        ),
    ]
