from django import forms


class PuzzleForm(forms.Form):
    
    s11 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s12 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s13 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s14 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s15 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s16 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s17 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s18 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s19 = forms.IntegerField(min_value=0, max_value=9, required=False)
    
    s21 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s22 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s23 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s24 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s25 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s26 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s27 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s28 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s29 = forms.IntegerField(min_value=0, max_value=9, required=False)
    
    s31 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s32 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s33 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s34 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s35 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s36 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s37 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s38 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s39 = forms.IntegerField(min_value=0, max_value=9, required=False)
    
    s41 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s42 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s43 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s44 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s45 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s46 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s47 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s48 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s49 = forms.IntegerField(min_value=0, max_value=9, required=False)
    
    s51 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s52 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s53 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s54 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s55 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s56 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s57 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s58 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s59 = forms.IntegerField(min_value=0, max_value=9, required=False)
    
    s61 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s62 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s63 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s64 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s65 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s66 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s67 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s68 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s69 = forms.IntegerField(min_value=0, max_value=9, required=False)
    
    s71 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s72 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s73 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s74 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s75 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s76 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s77 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s78 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s79 = forms.IntegerField(min_value=0, max_value=9, required=False)
    
    s81 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s82 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s83 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s84 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s85 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s86 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s87 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s88 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s89 = forms.IntegerField(min_value=0, max_value=9, required=False)
    
    s91 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s92 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s93 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s94 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s95 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s96 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s97 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s98 = forms.IntegerField(min_value=0, max_value=9, required=False)
    s99 = forms.IntegerField(min_value=0, max_value=9, required=False)
